env:
  browser: true
  es6: true
  node: true
  jest/globals: true
extends:
  # - 'plugin:vue/essential'
  # - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:eslint-plugin-sonarjs/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - 'eslint-plugin-sonarjs'
  - jest
  # - vue
  - '@typescript-eslint'
  # - typescript
ignorePatterns:
  - '*.d.ts'
  - 'node_modules/'
  - 'dist/'
  - '**/i18n/*.ts'
rules:
  '@typescript-eslint/member-delimiter-style': off
  # '@typescript-eslint/interface-name-prefix':
  #   prefixWithI: always

